name: Build

on:
  push:
    branches: [main]
    tags:
      - v*
  pull_request:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Build
        run:
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build src/main.go

      - name: 'Login via Azure CLI'
        if: startsWith(github.ref, 'refs/tags/v')
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_RBAC_CREDENTIALS }}

      - name: 'Publish to Azure Functions'
        if: startsWith(github.ref, 'refs/tags/v')
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        env:
          AZURE_FUNCTIONAPP_NAME: 'test-myfunction1'
          AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'

      - name: 'Upload to blob storage'
        if: startsWith(github.ref, 'refs/tags/v')
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az storage blob upload-batch --account-name ${{ env.AZURE_STORAGE_NAME }} -d '$web' -s src/resources --overwrite
        env:
          AZURE_STORAGE_NAME: 'myappfunction1'
